name: reqif_editor
description: "A graphical editor for ReqIF documents."

homepage: https://domohuhn.github.io/reqif_editor/
repository: https://github.com/domohuhn/reqif_editor
issue_tracker: https://github.com/domohuhn/reqif_editor/issues

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.6.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  xml: ^6.6.1
  file_picker: ^10.3.2
  flutter_quill: ^11.4.1
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  two_dimensional_scrollables: ^0.3.7
  path: ^1.8.3
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
