name: reqif_editor
description: "A graphical editor for ReqIF documents."

homepage: https://domohuhn.github.io/reqif_editor/
repository: https://github.com/domohuhn/reqif_editor
issue_tracker: https://github.com/domohuhn/reqif_editor/issues

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.3.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  xml: ^6.0.0
  file_picker: ^6.1.1
  flutter_quill: ^9.1.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  two_dimensional_scrollables: ^0.1.0
  flutter_fancy_tree_view: ^1.4.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_oss_licenses: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
